# Generated by Django 4.2.1 on 2023-07-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entry_type', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
