# Generated by Django 4.2.1 on 2023-07-26 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('given_by', models.CharField(max_length=100)),
                ('taken_by', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('remarks', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeentry')),
            ],
        ),
    ]
